### ISSUE TITLE
"extract_path" is required

### ISSUE THREAD

**Issue by rvdh** [voxpupuli/puppet-mysql_java_connector#11]
```
class { 'mysql_java_connector':
  links   => [ "${jira_target}/lib" ],
  version => '5.1.36',
}
```

This fails:
`Error: Could not set 'present' on ensure: missing archive extract_path at 24:/modules/mysql_java_connector/manifests/install.pp`

When I add

```
Archive {
  extract_path => '/tmp'
}
class { 'mysql_java_connector':
  links   => [ "${jira_target}/lib" ],
  version => '5.1.36',
}
```

It works correctly.

**Comment by igalic** [comment]
i wonder if that's a regression in puppet-archive 1.0.0?

**Comment by tykeal** [comment]
If it is, it's still affecting puppet-archive 1.1.2. I just ran into this myself after adding this module to manage in the connector for use with puppet-confluence.
