### ISSUE TITLE
Stagig file and extract should not use $file

### ISSUE THREAD

**Issue by jg-development** [voxpupuli/puppet-mysql_java_connector#4]
Hi,

the using of only "$file" as a staging::file and staging::extract parameter can result in conflicts,
if the mysql-connector is used by different modules.
(stash, confluence, jira, bamboo)
A better aproach would be using the full path like:

``` ruby
  staging::file { "${installdir}/${file}":
    target => "${installdir}/${file}",
    source  => "${downloadURL}/${file}",
    timeout => 300,
  } ->

  staging::extract { "${installdir}/${file}":
    source => "${installdir}/${file}",
    target  => $installdir,
    creates => "${installdir}/${product}-${version}",
  } ->
```

Greetings Jan

**Comment by igalic** [comment]
@jg-development would you mind adding a patch?

**Comment by jyaworski** [comment]
What's the status of this?

**Comment by alexjfisher** [comment]
The module is now using `puppet-archive`, so closing this.
